return {
  "glepnir/dashboard-nvim",
  event = "VimEnter",
  opts = {
    theme = "doom",
    config = {
      header = {
        "                                                     ",
        "                  ⢀⣀⣤⣤⣤⣶⣶⣶⣶⣶⣶⣤⣤⣤⣀⡀                   ",
        "              ⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⡀             ",
        "            ⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⡀           ",
        "           ⣴⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄          ",
        "         ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀        ",
        "        ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀       ",
        "        ⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧       ",
        "        ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿       ",
        "       ⢸⣿⣿⣿⣿⠟⠋⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠙⠻⣿⣿⣿⣿⣿⣿⡇      ",
        "       ⢸⣿⣿⣿⣿⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣿⣿⣿⣿⣿⣿⡇      ",
        "       ⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇      ",
        "       ⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇      ",
        "       ⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇      ",
        "       ⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇      ",
        "       ⠘⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠟⠃      ",
        "                                                     ",
        "                   Neovim IDE Setup                 ",
        "                                                     ",
      },
      center = {
        {
          icon = " ",
          icon_hl = "Title",
          desc = "Find File",
          desc_hl = "String",
          key = "f",
          key_hl = "Number",
          action = "Telescope find_files",
        },
        {
          icon = " ",
          icon_hl = "Title",
          desc = "Recent Files",
          desc_hl = "String",
          key = "r",
          key_hl = "Number",
          action = "Telescope oldfiles",
        },
        {
          icon = " ",
          icon_hl = "Title",
          desc = "Find Word",
          desc_hl = "String",
          key = "w",
          key_hl = "Number",
          action = "Telescope live_grep",
        },
        {
          icon = " ",
          icon_hl = "Title",
          desc = "New File",
          desc_hl = "String",
          key = "n",
          key_hl = "Number",
          action = "enew",
        },
        {
          icon = " ",
          icon_hl = "Title",
          desc = "Config",
          desc_hl = "String",
          key = "c",
          key_hl = "Number",
          action = "e ~/.config/nvim/",
        },
        {
          icon = " ",
          icon_hl = "Title",
          desc = "Lazy",
          desc_hl = "String",
          key = "l",
          key_hl = "Number",
          action = "Lazy",
        },
        {
          icon = " ",
          icon_hl = "Title",
          desc = "Quit",
          desc_hl = "String",
          key = "q",
          key_hl = "Number",
          action = "qa",
        },
      },
      footer = function()
        local stats = require("lazy").stats()
        local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
        return { "⚡ Neovim loaded " .. stats.loaded .. "/" .. stats.count .. " plugins in " .. ms .. "ms" }
      end,
    },
  },
  dependencies = { "nvim-tree/nvim-web-devicons" }
}
